{% set name = "napari-blossom" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-blossom-{{ version }}.tar.gz
  sha256: 0aea29fe92878b75ab430e8d61c8da5046de42c22b95f3a2fa19b76af4dcd39f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - focal-loss
    - magicgui
    - napari
    - numpy
    - opencv
    - python >=3.8
    - qtpy
    - scikit-image
    - tensorflow

test:
  imports:
    - napari_blossom
  commands:
    - pip list
    # - pip check  # Fails due to opencv-python-headless
  requires:
    - pip

about:
  home: https://github.com/hereariim/napari-blossom
  summary: Segmentation of blossom apple tree images
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - hereariim
    - jaimergp
